strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      libnode_x86: '0'
    mac:
      imageName: 'macos-10.13'
      libnode_x86: '0'
    win_x64:
      imageName: 'windows-2019'
      libnode_x86: '0'
    win_x86:
      imageName: 'windows-2019'
      libnode_x86: '1'

variables:
  libnode_config_flags: --without-intl
  libnode_zip_suffix: '-nointl'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- script: |
    python -m scripts.download
  displayName: 'Download source code of Node.js'

- script: |
    python -m scripts.build
  displayName: 'Build'

- script: |
    python -m scripts.postproc
  displayName: 'Postprocess'

- script: |
    python -m scripts.archive
  displayName: 'Archive'
