trigger:
- master


variables:
  LIBNODE_NODE_VERSION: 'v11.14.0'

jobs:
  - job: build
    strategy:
      matrix:
        linux:
          LIBNODE_X86: '0'
          imageName: 'ubuntu-16.04'
        mac:
          LIBNODE_X86: '0'
          imageName: 'macos-10.13'
        win_x64:
          LIBNODE_X86: '0'
          imageName: 'vs2017-win2016'
        win_x86:
          LIBNODE_X86: '1'
          imageName: 'vs2017-win2016'

    pool:
      vmImage: $(imageName)

    variables:
      LIBNODE_CONFIG_FLAGS: '--without-intl'
      LIBNODE_ZIP_SUFFIX: '-nointl'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7'
        addToPath: true
        architecture: 'x64'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.5'
        addToPath: false
        architecture: 'x64'

    - bash: |
        $USEPYTHONVERSION2_PYTHONLOCATION/python -m scripts.download
      displayName: 'Download source code of Node.js'

    - bash: |
        $USEPYTHONVERSION2_PYTHONLOCATION/python -m scripts.build
      displayName: 'Build'

    - bash: |
        $USEPYTHONVERSION2_PYTHONLOCATION/python -m scripts.postproc
      displayName: 'Postprocess'

    - bash: |
        output=$($USEPYTHONVERSION2_PYTHONLOCATION/python -m scripts.archive)
        echo "##vso[task.setvariable variable=zip_file;]$output"
      displayName: 'Archive'
    
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: $(zip_file)
        pathtoPublish: $(zip_file)
        
  - job: gh_release
    dependsOn: build
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadType: 'specific'
        downloadPath: $(Build.ArtifactStagingDirectory)
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: 'GitHub connection 1'
        repositoryName: patr0nus/libnode
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'manual'
        tag: 'libnode-$(LIBNODE_NODE_VERSION)'
        assets: '$(Build.ArtifactStagingDirectory)/*/*'
        isDraft: false
        addChangeLog: false
