strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      libnode_x86: '0'
    mac:
      imageName: 'macos-10.13'
      libnode_x86: '0'
    win_x64:
      imageName: 'windows-2019'
      libnode_x86: '0'
    win_x86:
      imageName: 'windows-2019'
      libnode_x86: '1'

pool:
  vmImage: $(imageName)

variables:
  libnode_config_flags: '--without-intl'
  libnode_zip_suffix: '-nointl'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- task: UsePythonVersion@0
  inputs:
    versionSpec: 2.7
    architecture: 'x64'


- script: |
    python3 -m scripts.download
  displayName: 'Download source code of Node.js'

- script: |
    python3 -m scripts.build
  displayName: 'Build'

- script: |
    python3 -m scripts.postproc
  displayName: 'Postprocess'

- script: |
    python3 -m scripts.archive
  displayName: 'Archive'
