strategy:
  matrix:
    linux:
      LIBNODE_X86: '0'
      imageName: 'ubuntu-16.04'
    mac:
      LIBNODE_X86: '0'
      imageName: 'macos-10.13'
    win_x64:
      LIBNODE_X86: '0'
      imageName: 'windows-2019'
    win_x86:
      LIBNODE_X86: '1'
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

variables:
  LIBNODE_CONFIG_FLAGS: '--without-intl'
  LIBNODE_ZIP_SUFFIX: '-nointl'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    addToPath: true
    architecture: 'x64'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.5'
    addToPath: false
    architecture: 'x64'

- script: '$(pythonPath.pythonLocation)/python -m scripts.download'
  displayName: 'Download source code of Node.js'

- script: '$(pythonPath.pythonLocation)/python -m scripts.build'
  displayName: 'Build'

- script: '$(pythonPath.pythonLocation)/python -m scripts.postproc'
  displayName: 'Postprocess'

- script: '$(pythonPath.pythonLocation)/python -m scripts.archive'
  displayName: 'Archive'
